### ISSUE TITLE
Consolidate various vars

### ISSUE THREAD

**Issue by mrlesmithjr** [mrlesmithjr/ansible-vsphere-management#20]
Need to consolidate various vars into a higher abstraction. This will allow for a more centralized method of defining certain variables. For example, here are a few:
```yaml
vsphere_linux_vapp_ovf: C:\vagrant\vApps\ubuntu_16.04_template.ovf

vsphere_vm_services_subnet_mask: 255.255.255.0

vsphere_vm_services_subnet_mask_cidr: 24

vsphere_vm_services_vswitch: VSS-VLAN-102
```
