### ISSUE TITLE
Consolidate IP Subnet/Addressing

### ISSUE THREAD

**Issue by mrlesmithjr** [mrlesmithjr/ansible-vsphere-management#3]
Need to consolidate IP Subnet/Addressing into a more flexible format to minimize the number of places to update IP address info in case of a subnet change. Also need to prepare for multiple subnet definitions following the same methodology.

Examples to leverage:
```yaml
# vSphere host managment subnet
vsphere_management_subnet: 10.0.101

# vSphere core services for vms
vsphere_vm_services_subnet: 10.0.102

# vSphere host vMotion subnet
vsphere_vmotion_subnet: 10.0.120

# vSphere host storage subnet - NFS
vsphere_storage_subnet: 10.0.127
```

Based on the example above then define variables such as:
```yaml
vsphere_ddi_vm_ips:
  - "{{ vsphere_vm_services_subnet }}.10"
  - "{{ vsphere_vm_services_subnet }}.11"
  - "{{ vsphere_vm_services_subnet }}.12"

vsphere_dnsdist_vm_ips:
  - "{{ vsphere_vm_services_subnet }}.40"
  - "{{ vsphere_vm_services_subnet }}.41"
```
